name: 2 Export and Create Prerelease
on:
  workflow_dispatch:
#   push:
#     branches: [main, master]

permissions:
  contents: write

jobs:
  build_and_prerelease:
    name: Build and Create/Update Prerelease
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Get Current Date
        id: get_date
        run: echo "date_string=$(Get-Date -Format 'dd-MM-yyyy HH:mm:ss UTC')" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Determine Comparison Range for Changes
        id: comparison_info
        run: |
          LATEST_SEM_TAG=$(git tag -l "v[0-9]*.[0-9]*.[0-9]*" --sort=-v:refname | head -n 1)
          REPO_URL="https://github.com/${{ github.repository }}"

          if [ -z "$LATEST_SEM_TAG" ]; then
            echo "Kein semantischer Release-Tag für den Vergleich gefunden."
            if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.event.before }}" != "0000000000000000000000000000000000000000" ]; then
              CHANGES_LINE="Changes in this push: ${REPO_URL}/compare/${{ github.event.before }}...${{ github.sha }}"
            else
              CHANGES_LINE="Changes up to commit: ${REPO_URL}/commit/${{ github.sha }}"
            fi
          else
            echo "Letzter semantischer Tag: $LATEST_SEM_TAG"
            CHANGES_LINE="Changes since ${LATEST_SEM_TAG}: ${REPO_URL}/compare/${LATEST_SEM_TAG}...${{ github.sha }}"
          fi
          echo "changes_display_line=$CHANGES_LINE" >> $GITHUB_OUTPUT
        shell: bash

      - name: Run export script
        shell: cmd
        working-directory: ./helper/export
        run: run.bat

      - name: Create or Update Prerelease
        uses: softprops/action-gh-release@v2
        with:
          tag_name: prerelease
          name: Latest Prerelease # Name des Prereleases
          body: |
            This prerelease was automatically generated and contains the latest changes.

            ## Latest Export
            - Generated: ${{ steps.get_date.outputs.date_string }}
            - Latest commit: [`${{ github.sha }}`](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            - ${{ steps.comparison_info.outputs.changes_display_line }}
            - Branch: `${{ github.ref_name }}`
          draft: false
          prerelease: true
          files: ./helper/export/ioi-testing.zip
